### ISSUE TITLE
Ask for help with another bus data

### ISSUE THREAD

**Issue by KhaledAlkilane89** [rorinr/bus_line_analysis#1]
hello, 
I am sorry for posting here but I can't find any contact for you.
while you work with bus data, Can you please help me to solve this problem 
https://stackoverflow.com/questions/66002220/how-to-gather-buses-enter-exit-stations-records-into-trips-to-give-unique-id-an
in my bus data. However, can I know how you process NaN values for stops time in your data
really appreciate any help. thanks in advance

**Comment by rorinr** [comment]
Hello, 
do you still need help? i see there are some answers in your stackoverflow question. 
If there are 3 stops, stop 'A', stop 'B' and stop 'C'. And i know delay of 'A' and delay of 'C', i calculated an average of these 2 delay for stop 'B'. I am not sure if this was your question, i would appreciate it to help you, so if there are any open question, just send me a message. You can also send an email to robinpierschke@yahoo.de
